apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql-root-user: "root"
  mysql-user-pass: "root"
---
apiVersion: v1
kind: Service
metadata:
        name: mysql-master
        labels:
          app: mysql-master
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: mysql-master
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: mysql-budget
spec:
  selector:
    matchLabels:
      app: mysql
  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-master
spec:
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-master
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - mysql-slave
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mysql-ha
        imagePullPolicy: Always
        image: daocloud.io/daocloud/mysql-ha
        resources:
          requests:
            memory: "100Mi"
        ports:
        - containerPort: 3306
          name: mysql-all
        env:
        - name : REPLICATION_MASTER
          value: '''true'''
        - name : MYSQL_USER
          valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql-root-user
        - name : MYSQL_PASS
          valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql-user-pass
 # volumeClaimTemplates:
 # - metadata:
 #     name: mysql-master-data
 #     annotations:
 #       volume.alpha.kubernetes.io/storage-class: anything
 #   spec:
 #     accessModes: [ "ReadWriteOnce" ]
 #     resources:
 #       requests:
 #         storage: 100Mi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-slave
spec:
  serviceName: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql-slave
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - mysql-master
              topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - mysql-slave
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mysql-ha
        imagePullPolicy: Always
        image: daocloud.io/daocloud/mysql-ha
        resources:
          requests:
            memory: "100Mi"
        ports:
        - containerPort: 3306
          name: mysql-all
        env:
        - name : REPLICATION_SLAVE
          value: '''true'''
        - name : MYSQL_USER
          valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql-root-user
        - name : MYSQL_PASS
          valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql-user-pass
        - name : MYSQL_PORT_3306_TCP_ADDR
          value: "$MYSQL_MASTER_SERVICE_HOST"
        - name : MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name : MYSQL_ENV_REPLICATION_USER
          valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql-root-user 
        - name : MYSQL_ENV_REPLICATION_PASS
          valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql-user-pass
 # volumeClaimTemplates:
 # - metadata:
 #     name: mysql-slave-data
 #     annotations:
 #       volume.alpha.kubernetes.io/storage-class: anything
 #   spec:
 #     accessModes: [ "ReadWriteOnce" ]
 #     resources:
 #       requests:
 #         storage: 100Mi
