version: '2'
services:
  rocketmqnamesrv1:
    labels:
      io.daocloud.dce.compose.endpoint-spec.mode: dnsrr
    volumes:
    - /data
    image: registry.cn-hangzhou.aliyuncs.com/weakiwi/rocketmq_docker
    ports:
    - 9876
    environment:
    - ROCKETMQ_ROLE=namesrv
    - SERVICENAME=rocketmqnamesrv1
  rocketmqnamesrv2:
    labels:
      io.daocloud.dce.compose.endpoint-spec.mode: dnsrr
    volumes:
    - /data
    image: registry.cn-hangzhou.aliyuncs.com/weakiwi/rocketmq_docker
    ports:
    - 9876
    environment:
    - ROCKETMQ_ROLE=namesrv
    - SERVICENAME=rocketmqnamesrv2
  amaster:
    labels:
      io.daocloud.dce.compose.endpoint-spec.mode: dnsrr
      # io.daocloud.dce.compose.placement.constraints: '["node.labels.rocketmqpool1==rocketmqpool1"]'
    volumes:
    - /data
    image: registry.cn-hangzhou.aliyuncs.com/weakiwi/rocketmq_docker
    ports:
    - 2379
    environment:
    - ROCKETMQ_ROLE=broker-a
    - SERVICENAME=amaster
  aslave:
    labels:
      io.daocloud.dce.compose.endpoint-spec.mode: dnsrr
      # io.daocloud.dce.compose.placement.constraints: '["node.labels.rocketmqpool1==rocketmqpool1"]'
    volumes:
    - /data
    image: registry.cn-hangzhou.aliyuncs.com/weakiwi/rocketmq_docker
    ports:
    - 2379
    environment:
    - ROCKETMQ_ROLE=broker-a-slave
    - SERVICENAME=aslave
  bmaster:
    labels:
      io.daocloud.dce.compose.endpoint-spec.mode: dnsrr
      # io.daocloud.dce.compose.placement.constraints: '["node.labels.rocketmqpool1==rocketmqpool1"]'
    volumes:
    - /data
    image: registry.cn-hangzhou.aliyuncs.com/weakiwi/rocketmq_docker
    ports:
    - 2379
    environment:
    - ROCKETMQ_ROLE=broker-b
    - SERVICENAME=bmaster
  bslave:
    labels:
      io.daocloud.dce.compose.endpoint-spec.mode: dnsrr
      # io.daocloud.dce.compose.placement.constraints: '["node.labels.rocketmqpool1==rocketmqpool1"]'
    volumes:
    - /data
    image: registry.cn-hangzhou.aliyuncs.com/weakiwi/rocketmq_docker
    ports:
    - 2379
    environment:
    - ROCKETMQ_ROLE=broker-b-slave
    - SERVICENAME=bslave
  rocketmq-console-ng:
    labels:
      io.daocloud.dce.compose.endpoint-spec.mode: dnsrr
      # io.daocloud.dce.compose.placement.constraints: '["node.labels.rocketmqpool1==rocketmqpool1"]'
    volumes:
    - /data
    image: styletang/rocketmq-console-ng
    ports:
    - 8080
    environment:
    - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmqnamesrv1:9876;rocketmqnamesrv2:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
